### ISSUE TITLE
chinachuとの連携

### ISSUE THREAD

**Issue by kouhgithub** [tsukumijima/EDCB#2]
プラグインで橋渡しする対応でいいのでchinachuとの連携が使えたらwindowsのEPGTimerでネットワーク録画予約出して
Chinachu側のパソコンで録画するって方法も出来て良いかなぁと思いまして

**Comment by tsukumijima** [comment]
私が Chinachu 環境を持っていませんし、元々このリポジトリは tkntrec さん版の EDCB の UI フォントを視認性の良くない MS ゴシック から Meiryo UI に変更したくらいの変更しか行っておらず、EDCB というシステムの内部をよく理解しているわけではないので、申し訳ありませんが私にはできません。
昨今では EPGStation の方が開発が活発なので、そちらとの連携であればもしかすると先方が実装してくれるかもしれませんが…
